version: '3.9'

services:
    db:
      image: postgres:13
      restart: always
      env_file: 
          - .env
      # ports:
      #     - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
          - PGPORT=${POSTGRES_PORT}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - ./data/db:/var/lib/postgresql/data


    web:
      build: .
      command: >
        sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            pip install prophet &&
            python manage.py runserver 0.0.0.0:8001"
      ports:
        - "8001:8001"
      volumes:
        - .:/www
      depends_on:
        - db

    tasks:
      build: .
      command: >
        sh -c "pip install prophet &&
            python manage.py moex"
      volumes:
        - .:/www
      depends_on:
        - db